version: '3.7'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./datapostgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DATABASE=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  mysql:
    image: mysql:8.2.0
    ports:
      - '3306:3306'
    volumes:
      - ./datamysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass

  gate-simulator:
    build: .
    image: gate-simulator:1.0.0
    ports:
      - '9999:9999'
